.. _makefile.rst:

#############################
Makefile
#############################



============
HowTos
============

.. topic:: Pass argument to variables in command line

        Say you have a makefile like this:

	::

	      action:
	          echo argument is $(argument)

        You would then call it ``make action argument=something``

.. seealso::
   
   `Passing additional variables from command line ot make <http://stackoverflow.com/questions/2826029/passing-additional-variables-from-command-line-to-make>`_




============
Resources
============

- `g++ compiling <http://www.cs.fsu.edu/~jestes/howto/g++compiling.txt>`_
